### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by jasonrdavis** [dcarosone/scrape-cassini#3] opened 2015-08-20 17:36 UTC
Hi, 

I have the Perl environment installed on Windows, but I can't find the required modules:

libanyevent-http-perl 
libdatetime-format-natural-perl
liburi-perl

I tried looking for them in CPAN, and installing them in the Perl shell using this command:

C:\Windows\System32>cpanm Module::libanyevent-http-perl
! Finding Module::libanyevent-http-perl on cpanmetadb failed.
! Finding Module::libanyevent-http-perl () on mirror http://www.cpan.org failed.
! Couldn't find module or a distribution Module::libanyevent-http-perl

Any suggestions?

Thanks!

Jason Davis
The Planetary Society

**Comment by jasonrdavis** [comment] 2015-08-20 22:44
I figured this out. The sequence, using CPANM, that worked was:

cpanm AnyEvent --force
cpanm DateTime::Format::Natural
cpanm URI
cpanm AnyEvent::HTTP

**Comment by dcarosone** [comment] 2015-08-20 23:21
Sorry about that, Jason.   Those names from the README example are the Ubuntu packages that wrap the perl modules, because every packaging system is different, alas.  Glad you worked it out.

I'll update the readme to be a bit clearer.

Meanwhile, I've just pushed a fix for the corrupted image download on windows (issue #4).

**Comment by dcarosone** [comment] 2015-08-21 00:55
Jason, can you comment on why you needed the `--force` option for `AnyEvent`?  Ordinarily it would have been pulled in as a dependency from `AnyEvent::HTTP`, which is why I don't list it explicitly for the Ubuntu example.

I presume this failed for some reason, and so you manually added it with `--force` to work around that. Did it give any specific reason why it failed?

**Comment by jasonrdavis** [comment] 2015-08-21 02:28
Ah, I assumed that AnyEvent:HTTP was a dependency of AnyEvent -- not the other way around. So originally I was only installing AnyEvent and the script wasn't working. I got an install error once and then forced it, and then installed AnyEvent:HTTP. This was the procedure I used for my machine and I advised Emily to do the same. 

So, it's likely you only need to install AnyEvent:HTTP and it will work. Sorry, I'm a little rusty on this type of work.

**Comment by dcarosone** [comment] 2015-08-21 03:22
Ah, ok, makes sense. Which windows perl are you using? Strawberry?

I want to set up a windows test environment so I can confirm this, and perhaps polish a few other things; might as well use the same one you chose.

**Comment by jasonrdavis** [comment] 2015-08-21 16:35
Yep, Strawberry. Thanks!

**Closed as completed** 2018-08-08 04:38 UTC
